### ISSUE TITLE
Add student

### ISSUE THREAD

**Issue by nazlikaralar** [erdikoch/Dormitory-Management-System-Cs476#16]
While adding student, I sometimes get an error: Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string:"...."

**Comment by erdikoch** [comment]
if problem is parsing -->> http://examples.javacodegeeks.com/core-java/lang/numberformatexception/java-lang-numberformatexception-how-to-solve-numberformatexception/
